### ISSUE TITLE
Create installation profile / custom module/feature.

### ISSUE THREAD

**Issue by Decipher** [drupal-au/drupal.org.au#11]
As per #10 and #8, we need a custom module so that we can implement a deployment strategy; somewhere we can run _hook_update_N_ to push configuration changes and such.

Additionally, it would make as much sense to have an installation profile for this project so that anyone developing locally only needs to install the site with said installation profile and everything will be up and running for them with no need to enable certain modules by hand.

**Comment by Decipher** [comment]
Any thoughts on this? PR is up to date with master.

**Comment by rikki-iki** [comment]
Comments in PR

**Comment by rikki-iki** [comment]
Closing as outdated.
