### ISSUE TITLE
Slack invites are not working

### ISSUE THREAD

**Issue by Decipher** [drupal-au/drupal.org.au#13]
Slack invites module is having problems and throwing a very unhelpful error:

```
Notice: Undefined index: error in Drupal\slack_invite\Form\SlackInviteForm->submitForm()
```

That error just tells me that there is no error to display, which isn't exactly helpful in debugging the issue.

I have opened an issue with the module (https://www.drupal.org/node/2627054) and will write a patch so we can at least get some more information on why the modules isn't working.

**Comment by Decipher** [comment]
The issue turned out to be that the token of the Druplicon user didn't contain the correct scope, while during testing I didn't yet have that user or token and had been testing with my own which did have that scope.

I have opened an additional issue with the Slack Invite module to check that the user has the correct scope to prevent others having this issue in the future. https://www.drupal.org/node/2627060

As a current workaround (until we can get the Druplicon user promoted to admin) I've put my token back in place, which means everyone will be being invited by me.

**Comment by Decipher** [comment]
K, both patches I wrote have been committed to the Slack Invite module in the current dev release. It is worth getting the module updated to this version ASAP to ensure we don't encounter this issue again in the future.

**Comment by Decipher** [comment]
Strike that, the current dev is missing two commits, will have to wait for the next dev to be built, or use a GIT checkout.

Given that we aren't using makefiles, it's probably best to just wait it out as it should only be a matter of hours.

**Comment by rikki-iki** [comment]
Is this resolved? I'm sure we've had people joining since December

**Comment by rikki-iki** [comment]
Closing. Form is definitely working.
