### ISSUE TITLE
Add tests.

### ISSUE THREAD

**Issue by Decipher** [drupal-au/drupal.org.au#2]
The ensure that the community can actively contribute to the codebase without breaking any of the existing functionality we need to ensure that all functionality has tests.

At the moment, there isn't really any functionality so to say, but once any is added it will need to have associated tests.

**Comment by AlexSkrypnyk** [comment]
For the sake of simplicity, I suggest we start with simple web tests rather than Behat tests.

**Comment by Decipher** [comment]
DrupalTI has behat, simpletest and unit test runners and is dead easy to make work with a project like this. I don't think there's an reason to not have one type of tests over another: https://github.com/LionsAd/drupal_ti

In the end though, any tests are better than no tests, even if they are manual tests (shudder).

**Comment by rikki-iki** [comment]
Closing as outdated.
