### ISSUE TITLE
Move site files under 'docroot' dir

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupal-au/drupal.org.au#4]
I suggest all web files are moved under 'docroot' so that everything else can be safely sitting outside.

Everything else:
- CI files (configs etc.)
- local environment files and dirs
- patches
- other files

This model has proven to be the most robust and easy to maintain.

**Comment by Decipher** [comment]
If we are going to persist with a full Drupal codebase in GIT, then I second this. If we where to move to Makefiles (or Composer files) to prevent duplication of the codebase and enforce best practices in regards to patches, then I we can achieve the same goals without the need of a docroot.

**Comment by AlexSkrypnyk** [comment]
As far as I can see what is in the repo right now, we should move all these files into 'docroot' dir.
As for 'best practices' of using makefiles - it is good enough while building, but when site goes in BAU there won't be a way to build from makefile anymore with preserving all the content.

In any case, having web-related files in the separate directory would make it much cleaner.

**Comment by Decipher** [comment]
I agree, we are already down this road, and I don't plan on de-railing it yet (once I see evidence of hacked code and mis-managed patches, I might re-consider).

@alexdesignworks: Feel like making a PR to move the codebase into Docroot?

@cafuego: Without knowing the specifics of the server configuration, I have to assume this will have some effect that you (or whomever has server access, that has not yet been explained) will need to compensate?

**Comment by rikki-iki** [comment]
Closing as outdated.

**Comment by cafuego** [comment]
Who you callin outdated.

**Comment by rikki-iki** [comment]
@cafuego you!! haha not replying to a question asked 3 years ago 😛 

This will be moved to platform.sh so you won't need to worry about anymore! I'm assuming the new setup will have some such docroot / app folder.
